### ISSUE TITLE
Syntax Highlighting 

### ISSUE THREAD

**Issue by dlaub3** [gin-gonic/website#14]
It would be nice to use a theme with syntax highlighting. It makes reading code samples easier.

**Comment by thinkerou** [comment]
@dlaub3 yes

**Comment by dlaub3** [comment]
Should we fork the current theme? It appears the theme wasn't originally intended for code samples so I'm guessing they won't accept adding prism.js as a PR.

**Comment by appleboy** [comment]
@thinkerou @dlaub3 or change to another theme which has code Syntax Highlighting. I like the  style of Echo website: 

![guide___echo_-_high_performance__minimalist_go_web_framework](https://user-images.githubusercontent.com/21979/47193194-3699e800-d384-11e8-8695-599bb7bbebec.png)

The left sidebar is very useful to search what I want.

**Comment by dlaub3** [comment]
It would also be nice to look for a theme with Algolia integration. I believe they have a free tier as long as you display the logo in the search results. I like doc sites that use it. It may be something to setup later.

**Comment by thinkerou** [comment]
hugo could use multi-themes, and hope page more clean more better.

**Comment by appleboy** [comment]
We need two themes for a landing page and documentation.

**Comment by thinkerou** [comment]
Now have supported, please see #26
