### ISSUE TITLE
The first version Gin website have completed!

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/website#26]
Hi, @javierprovecho @appleboy @isgj @dlaub3 

As title and optimize later on.

~~Gin website build based on https://github.com/census-instrumentation/opencensus-website and not use git submodule but copy docdock theme.~~
Use `docsy` theme.

The feature https://gin-gonic.com/introduction/  come from https://gin-gonic.github.io/gin/, right?

TODO:

- [x] favicon svg and some image for Gin

- [ ] improve document, because only have example code have not explain

- [ ] improve directory, like: binding dir, rendering dir, middleware dir, and so on

- [x] optimize/update header nav / footer nav? update color?

- [x] Chinese translation dir

- [x] use git submodule?

- [x] add disqus?

**Comment by appleboy** [comment]
Hi @thinkerou @javierprovecho maybe we can apply the Free Discourse Hosting For Gin open source project.

see https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

like [drone](https://discourse.drone.io) or [gitea](https://discourse.gitea.io) forum

**Comment by thinkerou** [comment]
@appleboy look nice 👍

**Comment by thinkerou** [comment]
Add `disqus` for comment discuss.
