### ISSUE TITLE
Support multi-language

### ISSUE THREAD

**Issue by thinkerou** [gin-gonic/website#32]
Now have had English, Chinese and Japanese, but Chinese and Japanese only one page, I hope they also multi sub page like English version.

So, when visit https://gin-gonic.com/ is English version, and visit https://gin-gonic.com/ja/ is Japanese version, and visit https://gin-gonic.com/cn/ is Chinese version, and so on.

thanks!

- [x] directory change for supporting multi-language

- [x] Chinese

- [x] Japanese

**Comment by sairoutine** [comment]
I have a will to make a Japanese version. But I don't know how to construct multi sub page. If other language will have been served, I will follow it.

**Comment by thinkerou** [comment]
@sairoutine I add Japanese dir/url. like:
![image](https://user-images.githubusercontent.com/4488261/52894490-3819d680-31e5-11e9-82d8-245552b939c1.png)

but the content not split according to catalog listing:
![image](https://user-images.githubusercontent.com/4488261/52894510-7ca57200-31e5-11e9-9587-b5cc59de2448.png)

**Comment by sairoutine** [comment]
@thinkerou
Amazing! Thank you!

I'm going to split the japanese content.

**Comment by thinkerou** [comment]
@sairoutine thanks!

**Comment by easonlin404** [comment]
I would like enhance or translate for zh-tw docs, how can I start it?  I have no ideal for the construction. @thinkerou

**Comment by thinkerou** [comment]
Hi, @easonlin404 thanks!
1. you need to split `content/zh-tw/docs/_index.md` to `content/zh-tw/docs/*`
2. you can read `content/ja/docs/*`
3. other question please ping me

**Comment by easonlin404** [comment]
> Hi, @easonlin404 thanks!
> 
> 1. you need to split `content/zh-tw/docs/_index.md` to `content/zh-tw/docs/*`
> 2. you can read `content/ja/docs/*`
> 3. other question please ping me

Thanks for your reply. 👍

**Comment by lostfind** [comment]
I want to translate for Korean. Would you create directory for korean?
@thinkerou

**Comment by thinkerou** [comment]
@lostfind ok

**Comment by thinkerou** [comment]
@lostfind I should use `ko-kr`? like: `en`, `zh-cn`, `zh-tw`

**Comment by lostfind** [comment]
@thinkerou Yes! Thank you for your response 👍

**Comment by appleboy** [comment]
this issue should be close?

**Comment by thinkerou** [comment]
> this issue should be close?

yes
