### ISSUE TITLE
Chinese translation mistakes.

### ISSUE THREAD

**Issue by ganlvtech** [gin-gonic/website#35]
> It features a martini-like API with much better performance, up to 40 times faster thanks to httprouter.

up to 40 times faster thanks to [httprouter](https://github.com/julienschmidt/httprouter). Means 由于 [httprouter](https://github.com/julienschmidt/httprouter)，速度提高了40倍。

Not 比 [httprouter](https://github.com/julienschmidt/httprouter) 的速度快了40倍, which means 40 times faster than [httprouter](https://github.com/julienschmidt/httprouter).

_Originally posted by @ganlvtech in https://github.com/gin-gonic/website/pull/28_

**Comment by appleboy** [comment]
@ganlvtech PR Welcome :)
