### ISSUE TITLE
Add Google Analytic in website.

### ISSUE THREAD

**Issue by appleboy** [gin-gonic/website#51]
https://analytics.google.com/analytics

cc @thinkerou @javierprovecho

**Comment by thinkerou** [comment]
@appleboy I have added it https://github.com/gin-gonic/website/blob/master/config.toml#L63
but seem invalid, I fix it.

**Comment by thinkerou** [comment]
`google/docsy` not support it now, I commit one issue https://github.com/google/docsy/issues/48

**Comment by thinkerou** [comment]
about the issue, I commit one pull request for google/docsy https://github.com/google/docsy/pull/49

**Comment by thinkerou** [comment]
- [ ] add disqus

- [ ] disable sidebar search

**Comment by appleboy** [comment]
`disable sidebar search`?

**Comment by thinkerou** [comment]
@appleboy because docs page have two search: nav-top and sidebar, I only need nav-top search.

**Comment by appleboy** [comment]
@thinkerou OK.

**Comment by thinkerou** [comment]
@appleboy can see google analytics data from https://analytics.google.com/analytics/web/#/report-home/a42425385w194642473p190031493

**Comment by appleboy** [comment]
@thinkerou Yes.
