### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by cncal** [gin-gonic/website#67]
It says in [Quickstart](https://gin-gonic.com/docs/quickstart/#requirements):

> Go 1.7 or Go 1.8 will be no longer supported soon.

Is it a wrong expression?

**Comment by thinkerou** [comment]
@cncal thanks! You are right. please see https://github.com/gin-gonic/gin/pull/1631, it should be Go 1.6 and 1.7.

**Comment by cncal** [comment]
ok. I'm doing some translation for chinese documents. Should I mention the info that Go1.8 will be required soon in the doc?

**Comment by thinkerou** [comment]
@cncal yes

**Comment by cncal** [comment]
ok.
