### ISSUE TITLE
hugo server error

### ISSUE THREAD

**Issue by cncal** [gin-gonic/website#70]
os: windows 10
hugo version: 0.54.0
```sh
$ hugo server
Building sites … Total in 571 ms
Error: Error building site: "%root%\content\ja\_index.html:6:5": failed to extract shortcode: template for shortcode "blocks/cover" not found
```
Same error occured using 
```sh
$ npm install
$ hugo
```
 Am I missing any files?

**Comment by thinkerou** [comment]
@cncal sorry, I have not window system. I found one similar issue https://github.com/google/docsy/issues/18, you try to it, thanks!

**Comment by cncal** [comment]
Really sorry about it :(. I missed the `--recursive` tag when I `git clone`. It works now, thanks a lot.

**Comment by thinkerou** [comment]
@cncal OK~
