### ISSUE TITLE
use go mod

### ISSUE THREAD

**Issue by lxy9805287** [gin-gonic/website#79]
use go mod, has an error:
--------------------------
/Users/liping/go/pkg/mod/github.com/gin-gonic/gin@v1.4.0/binding/msgpack.go:12:2: unknown import path "github.com/ugorji/go/codec": ambiguous import: found github.com/ugorji/go/codec in multiple modules:
        github.com/ugorji/go v1.1.4 (/Users/liping/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
        github.com/ugorji/go/codec v0.0.0-20180831062425-e253f1f20942 (/Users/liping/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20180831062425-e253f1f20942)

**Comment by thinkerou** [comment]
https://github.com/gin-gonic/gin/issues/1673
