### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by arulraj123** [gin-gonic/website#83]
I created the project in my workspace and make the build by using 
   ~/go/src/hello1$ go build
->  and run the using below the commend
   ~/go/src/hello1$ ./hello1
-> It is working fie
    [GIN-debug] Listening and serving HTTP on :8080
But I opened the new terminal and run the same means it is not working

**Comment by thinkerou** [comment]
because your `8080` have used.

**Comment by arulraj123** [comment]
I set the path 
sudo vim /etc/profile 
 export GOPATH=$HOME/go 
 export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin 
Now It is working
